### PR TITLE
Allow React v15 or v16 to be used

### PR DESCRIPTION
**Pull request by ssmith353**
Fixes: https://github.com/metal/metal-react/issues/4

### CODE REVIEW

**Comment by mthadley** [comment]
Yea, `peerDependency` makes sense. You should be able to "bring your own" React. I suppose we could be pretty permissive and do something like `>=15.0.0`?

**Comment by jbalsas** [comment]
This is what we're using:

```
ReactDOM.render
ReactDOM.unmountComponentAtNode
React.createElement
```

So we should be able to accept any `peerDependency` that supports that set

**Comment by ssmith353** [comment]
Works for me :+1:

**Comment by ssmith353** [comment]
Updated to use peerDependencies instead. Tested and works for me locally.

**Comment by jbalsas** [comment]
Hey @ssmith353, I've merged and I'll release this right away... I think this needs a `major` version bump as it might break existing usage if someone is relying on the dependency to be brought in by this package. 

What do you think @mthadley?

**Comment by mthadley** [comment]
@jbalsas Agreed 👍

**Comment by ssmith353** [comment]
Awesome. Thanks guys!

**Pull request merged**
